import { AppPreview, HomeBg } from '@/assets'
import {
  Heading,
  Text
} from '@capelaum-packages/ignite-react-05-design-system-react'
import Head from 'next/head'
import Image from 'next/image'
import {
  BgImageWrapper,
  HomeContainer,
  HomeLeftContainer,
  HomeRightContainer
} from './styles'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Call | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <BgImageWrapper>
          <Image
            src={HomeBg}
            alt="Imagem de background de grade em cinza meio escuro"
          />
        </BgImageWrapper>

        <HomeLeftContainer>
          <Heading as="h1" size="4xl">
            Agendamento descomplicado
          </Heading>
          <Text size="lg">
            Conecte seu calendário e permita que as pessoas marquem agendamentos
            no seu tempo livre.
          </Text>
        </HomeLeftContainer>

        <HomeRightContainer>
          <Image
            priority
            src={AppPreview}
            alt="Calendário simbolizando a aplicação de agendamento em funcionamento."
            quality={100}
          />
        </HomeRightContainer>
      </HomeContainer>
    </>
  )
}
